areacode: 330000
url: http://10.33.16.95:8088/gwssi-stats
src: src
finishout: out
username: 10010001
password: 123456
driver: mysql
dburl: gs33:Gs33123456@tcp(localhost:3306)/gs33
table: wzhyup
primarykey: uuid
shadowtable: stwzhyup
fieldsize:
  - 2
  - 32
  - 18
  - 1
  - 9
  - 50
  - 100
  - 4
  - 1
  - 3
  - 1
  - 2
  - 1
  - 6
  - 15
  - 20
  - 20
  - 20
  - 6
  - 200
  - 6
  - 60
  - 200
  - 3000
  - 24
  - 3
  - 24
  - 1
  - 14
  - 40
  - 20
  - 1
  - 32
  - 100
  - 100
  - 50
  - 6
  - 6
  - 20
  - 3
  - 1
  - 1
  - 1
  - 1
  - 14
  - 14
